---
  - name: instalaçao mysql-server
    apt:
      pkg:
      - mysql-server
      - mysql-client
      - python3-mysqldb
      - libmysqlclient-dev
      update_cache: yes

  - name: criando usuario no banco mysql
    mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_password }}"
        priv: '*.*:ALL'
        host: "%"
        state: present

  - name: criando database wp
    mysql_db: 
        name: "wordpress"
        state: present